### ISSUE TITLE
Job specific rewards and punishments

### ISSUE THREAD

**Issue by Drahsid** [Felscream/DragoonMayCry#1]
Really neat plugin!
Right now it doesn't seem to do anything to reward the execution of the specific job the user is playing, so your ranking is pretty much dependent on not clipping your GCD, and your execution of fight mechanics.
I think this could be improved with simple job specific rewards and punishments.

For example, on Bard, you want near 100% DOT uptime (some exceptions,) though you also want to refresh your DOTs during the burst window. With this context, you could punish the player for not having their DOTs up, and reward the player for refreshing their DOTs when under raging strikes (and at max level, ideally Army's Muse, Battle Voice, and Radiant Finale.)

There's various small things like this, and I think it would make the results of the plugin more exciting.
I see that there is a enum of buff Ids, though it doesn't seem to be used. Is this something you're interested in implementing? I would be willing to contribute, at the very least for jobs I can play well.

**Comment by Felscream** [comment]
Hey, thanks for your comment.

Yeah adding job specific mechanics was something that I considered at the beginning but I wanted to get the core of the plugin out bug free (and there are still lots of bugs) before considering adding them.
And then I realized that if I wanted to add them, that may require too much maintenance with each patch depending on what SE would change / what the balance finds optimal. Some plugins do it, but I don't think I can.

**Comment by Drahsid** [comment]
Hah, to be fair I'm not sure a single person could implement something like that for every single job. That is a lot to keep track of, especially if you're not a top player on literally every job.
I think if this did happen, as I mentioned the rewards/punishments would have to follow pretty simple logic, and would just have to be an implemented for specific jobs, rather than all or nothing.
In any case, if you do end up adding this, I would be willing to implement the jobs I am privy to!
