### ISSUE TITLE
Request: option for Local Sound files

### ISSUE THREAD

**Issue by Prissyking** [Felscream/DragoonMayCry#24]
Hi, wasn't sure where to ask this so I can delete it if necessary, love this plugin it's breathed new life into my gameplay, 
I saw it's got the selection of music from DMC5 which I appreciate, would it be possible to add a 'browse local files' option as well, and give it a file path for an mp3 or wav on the local hard drive and use that instead? 
I think that'd help secure the longevity of the plugin by allowing for an infinite number of music tracks for the player. Cheers to you

**Comment by Felscream** [comment]
Are you only talking about local files for the announcer or the dynamic BGM as well ?

**Comment by Prissyking** [comment]
Oh sorry I should have been more specific. Dynamic BGM. 
Announcer options are already sufficient I think.
I have many ideas for songs that would fit this plugin and just an option to point the plugin to a file name would be handy.
There's a plugin called 'Hit it, Joe!' that adds custom sounds to critical hits and it uses a similar file path system where it allows you to enter a file path for sound files on your hard drive, that's what made me think of it.

**Comment by Felscream** [comment]
I'll try to work on it. No ETA, this will take a long time since the dynamic BGM system is a dumpster fire and I can't believe that it is currently working.

**Comment by Prissyking** [comment]
Haha, no problem. I figured it might be more complicated than it seemed at first since I'm not sure how complex the system is or how many different versions of the songs there were. Thanks for the reply
