### ISSUE TITLE
Handle default output device changes

### ISSUE THREAD

**Issue by Felscream** [Felscream/DragoonMayCry#8]
The plugin won't detect if the system's default audio output device changes after initialization.

**Comment by tri739** [comment]
This sounds quite a bit like what I was just experiencing. If the plugin was active when switching audio outputs the game would cease to play audio from any output until it was restarted. Attempting to disable the plugin in this state would result in the game freezing indefinitely.

**Comment by Felscream** [comment]
Thank you for your report, I broke it in the last update, should be good in the next one.
https://github.com/Felscream/DragoonMayCry/commit/b68a2dd0faac74c3eabc0ae3db097c6a341ef852
